### ISSUE TITLE
Plugin does not work with ES 2.2.0

### ISSUE THREAD

**Issue by phutchins** [elastic/elasticsearch-cloud-gce#56]
Get complaints about java permissions but adding them doesn't seem to fix... 

`[2016-02-05 11:39:42,346][WARN ][discovery.gce            ] [homer] Exception caught during discovery: access denied ("java.lang.RuntimePermission" "setFactory")
java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "setFactory")
        at java.security.AccessControlContext.checkPermission(AccessControlContext.java:372)
        at java.security.AccessController.checkPermission(AccessController.java:559)
        at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
        at java.lang.SecurityManager.checkSetFactory(SecurityManager.java:1625)
        at javax.net.ssl.HttpsURLConnection.setSSLSocketFactory(HttpsURLConnection.java:362)
        at com.google.api.client.http.javanet.NetHttpTransport.buildRequest(NetHttpTransport.java:145)
        at com.google.api.client.http.javanet.NetHttpTransport.buildRequest(NetHttpTransport.java:62)
        at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:863)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:419)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:352)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:469)
        at org.elasticsearch.cloud.gce.GceComputeServiceImpl$1$1.run(GceComputeServiceImpl.java:94)
        at org.elasticsearch.cloud.gce.GceComputeServiceImpl$1$1.run(GceComputeServiceImpl.java:90)
        at java.security.AccessController.doPrivileged(Native Method)
`

**Comment by dadoonet** [comment]
Can you open this on https://github.com/elastic/elasticsearch?

It's not maintained anymore here after 2.0.

**Comment by phutchins** [comment]
Sure thing. Done. Thanks!
